name: Pull Request Quality Check

on:
  pull_request:
    branches:
      - 'DIC1-*'
      - 'IS-*'

jobs:
  quality-check:
    runs-on: ubuntu-latest

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name:  Checkout du code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name:  Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name:  Scan de secrets avec Gitleaks
        uses: zricethezav/gitleaks-action@v2
        continue-on-error: false

      - name:  Scan des vulnérabilités avec OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "todos"
          path: "./"
          format: "HTML"
          out: "dependency-check-report"

      - name:  Tests unitaires
        run: mvn clean test

      - name:  Analyse SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: your-org_todos
          SONAR_ORGANIZATION: your-org

      - name:  Vérification du Quality Gate
        uses: SonarSource/sonarcloud-quality-gate-action@master
        with:
          scanTimeout: 300
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
